contracts_dir: src
solc: "0.8.20"
solc_optim: True
loop_iter: 4
prover_args: [
    "-depth 20",
    "-smt_hashing_scheme plaininjectivity"
]
verify: WhiteRockPass:certora/specs/WhiteRockPass.spec
verify: BookingEscrow:certora/specs/BookingEscrow.spec
